name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: 3DMovement
  PROJECT_PATH: Godot3dMovement

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          cd ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls -l
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          ls -l
          godot -v --headless --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          cd ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          ls -l
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --headless --export-release "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: 3D Movement
          ITCH_USER: FollowTheDopamine
          PACKAGE: project/${{ env.EXPORT_NAME }}/build/web
# name: "godot-ci export"
# on:
#   push:
#     branches: [master]

# env:
#   GODOT_VERSION: 3.3.4
#   EXPORT_NAME: test-project
#   PROJECT_PATH: test-project

# jobs:
#   export-windows:
#     name: Windows Export
#     runs-on: ubuntu-20.04
#     container:
#       image: barichello/godot-ci:3.3.4
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           lfs: true
#       - name: Setup
#         run: |
#           mkdir -v -p ~/.local/share/godot/templates
#           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#       - name: Windows Build
#         run: |
#           mkdir -v -p build/windows
#           cd $PROJECT_PATH
#           godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: windows
#           path: build/windows

#   export-linux:
#     name: Linux Export
#     runs-on: ubuntu-20.04
#     container:
#       image: barichello/godot-ci:3.3.4
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           lfs: true
#       - name: Setup
#         run: |
#           mkdir -v -p ~/.local/share/godot/templates
#           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#       - name: Linux Build
#         run: |
#           mkdir -v -p build/linux
#           cd $PROJECT_PATH
#           godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: linux
#           path: build/linux

#   export-web:
#     name: Web Export
#     runs-on: ubuntu-20.04
#     container:
#       image: barichello/godot-ci:3.3.4
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           lfs: true
#       - name: Setup
#         run: |
#           mkdir -v -p ~/.local/share/godot/templates
#           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#       - name: Web Build
#         run: |
#           mkdir -v -p build/web
#           cd $PROJECT_PATH
#           godot -v --export "HTML5" ../build/web/index.html
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: web
#           path: build/web
#       - name: Install rsync 📚
#         run: |
#           apt-get update && apt-get install -y rsync
#       - name: Deploy to GitHub Pages 🚀
#         uses: JamesIves/github-pages-deploy-action@releases/v4
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: build/web # The folder the action should deploy.

#   export-mac:
#     name: Mac Export
#     runs-on: ubuntu-20.04
#     container:
#       image: barichello/godot-ci:3.3.4
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           lfs: true
#       - name: Setup
#         run: |
#           mkdir -v -p ~/.local/share/godot/templates
#           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#       - name: Mac Build
#         run: |
#           mkdir -v -p build/mac
#           cd $PROJECT_PATH
#           godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: mac
#           path: build/mac
# # Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

# name: godot-ci

# on:
#   push:
#     branches: [master]

# env:
#   EXPORT_NAME: 3D Movement
#   GODOT_VERSION: 3.4.2

# jobs:
#   export-web:
#     name: Web Export
#     runs-on: ubuntu-latest
#     container:
#       image: barichello/godot-ci:3.4.2
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Setup
#         run: |
#           mkdir -v -p ~/.local/share/godot/templates
#           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
#           apt-get update && apt-get install -y rsync

#       - name: Web Build
#         run: |
#           cd project
#           mkdir ./$EXPORT_NAME
#           rsync -Rr . ./$EXPORT_NAME
#           cd $EXPORT_NAME
#           mkdir -v -p build/web
#           godot -v --export "HTML5" build/web/index.html

#       - name: Upload Artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: web
#           path: project/${{ env.EXPORT_NAME }}/build/web

#       - name: Publish to itch.io
#         uses: josephbmanley/butler-publish-itchio-action@v1.0.2
#         env:
#           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
#           CHANNEL: web
#           ITCH_GAME: 3D Movement
#           ITCH_USER: FollowTheDopamine
#           PACKAGE: project/${{ env.EXPORT_NAME }}/build/web

#       # - name: Notify Discord Channel
#       #   env:
#       #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#       #   uses: Ilshidur/action-discord@0.3.0
#       #   with:
#       #     args: "A game update is available at https://NAME-OF-YOUR-USER.itch.io/NAME-OF-YOUR-GAME !"
